services:
  #php
  #ngingx
  web_server:
    image: nginx:latest
    ports:
      - "81:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network-php-mysql
  app:
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    networks:
      - network-php-mysql
  #mysql
  db:
    image: mysql:8.0
    # volumes:
    #   - mysqldata:/var/lib/mysql
    #   #De manera automatica y optimizada, docker va a decidir donde guardar la data
    ports:
      - "3307:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASS}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASS}
      MYSQL_DATABASE: ${DATABASE_NAME}
    depends_on:
      - web_server
    networks:
      - network-php-mysql

networks:
  network-php-mysql:
